# Generated by Django 5.0 on 2023-12-27 14:02

import main.apps
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="image",
            field=models.ImageField(upload_to=main.apps.user_directory_path),
        ),
    ]
