# Generated by Django 5.0 on 2024-01-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_document_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
